#!/bin/bash
set -e
#set -x

BASE_DIR="/var/www/drupal/sites/all/modules"
MODULE_FILE="/vagrant/islandora-module-list-sans-tuque.txt"

usage () {
  echo "Usage "`basename $0`": (-p | -f | -b <branch>)"
  echo "  -p            : pull new updates to the current branch"
  echo "  -f            : fetches updates and new branches"
  echo "  -b (<branch>) : list branches or check out <branch>"
  echo "  -q <file>     : archive current commits to file <file>"
  echo "  -r <file>     : revert to commits in backup <file>"
}

git_list_branch () {
  git branch
}

git_pull () {
  sudo git reset --hard
  sudo git pull
}

git_fetch () {
  sudo git fetch origin
}

git_checkout () {
  BRANCH=$1

  # This slows it down, but is kind of im
  git_fetch

  # List the branches we have
  CURRENT=$(git branch)
  # Strip the *s
  CURRENT=$(echo "$CURRENT" | sed 's/\*//g')
 
  # Loop on newline
  while IFS=$'\n' read -ra ADDR; do
      for i in "${ADDR[@]}"; do
        # Strip leading and trailing spaces
        i=$(echo "$i" | sed 's/^\s*\b//' | sed 's/\b\s*$//')
        # if we have a match, then just checkout the branch
        if [ "$BRANCH" = "$i" ]; then
          sudo git checkout ${BRANCH}
          return
        fi
      done
  done <<< "$CURRENT"

  # If you have changes you can't switch branches.
  # Eventually a switch here might be a good idea?
  #sudo git reset --hard

  # Otherwise check it out from origin
  sudo git checkout -b ${BRANCH} origin/${BRANCH}
}

git_archive () {
  local FILE=$1
  local HASH=$(git rev-parse HEAD)
  echo "$PWD $HASH" >> $FILE
}

git_revert () {
  local LFILE=$1
  local LINE=$(grep -e "$PWD " $LFILE)
  local HASH=$(echo "$LINE" | cut -d' ' -f2)
  echo "Reverting to hash $HASH"
  sudo git checkout -q ${HASH}
}

# We only accept 1 or 2 arguments
if [ $# -lt 1 -o $# -gt 2 ]; then
  usage
  exit 1
fi

# Parse arguments
if [ $# -eq 1 ]; then
  if [ "$1" = "-b" ]; then
    ACTION="list_branch"
  elif [ $# -eq 2 -a "$1" != "-p" ]; then
    echo "Error: unknown argument"
    usage
    exit 3
  elif [ "$1" = '-f' ]; then
    ACTION="fetch"
  elif [ "$1" = '-p' ]; then
    ACTION="pull"
  else
    usage
    exit 0
  fi
else
  if [ "$1" = "-p" ]; then
    echo "-p does not take any other arguments, perhaps you meant -b?"
    usage
    exit 4
  elif [ "$1" = '-r' ]; then
    ACTION="revert"
    FILE="$2"
  elif [ "$1" = '-a' ]; then
    ACTION="archive"
    FILE="$2"
    echo "Writing hashes to $FILE"
  elif [ "$1" = "-b" ]; then
    ACTION="checkout"
    BRANCH="$2"
  else
    echo "Error: unknown argument"
    usage
    exit 3
  fi
fi

# Do the loops
while read -r line; do
  if [ -d "$BASE_DIR/$line" ]; then
    echo "Acting on $line"
    cd "$BASE_DIR/$line"
    if [ "$ACTION" = "checkout" ]; then
      git_checkout ${BRANCH}
    elif [ "$ACTION" = "archive" -o "$ACTION" = "revert" ]; then
      git_$ACTION ${FILE}
    else
      git_$ACTION
    fi
  fi
done < $MODULE_FILE

exit 0
